/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.13
 * Generated at: 2022-05-25 09:11:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import java.io.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

 Connection conn=null;
  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      groceryDatabase.DB obj = null;
      obj = (groceryDatabase.DB) _jspx_page_context.getAttribute("obj", jakarta.servlet.jsp.PageContext.PAGE_SCOPE);
      if (obj == null){
        obj = new groceryDatabase.DB();
        _jspx_page_context.setAttribute("obj", obj, jakarta.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("    <html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <title>The Groccery Store</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"./style.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"./pages/ShopingListPage/style.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"./assets/CSS/popupStyle.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css\"\r\n");
      out.write("            integrity=\"sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==\"\r\n");
      out.write("            crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"displayFlexCont\">\r\n");
      out.write("                <div class=\"navBarContainer\">\r\n");
      out.write("                    <section class=\"header navbar\">\r\n");
      out.write("                        <div class=\"logoName\">\r\n");
      out.write("                            <div class=\"logoSVG\">\r\n");
      out.write("                                <img src=\"./assets/icons/Logo (2).svg\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"logoTXT\">The Grocery Store</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"searchAndLocation\">\r\n");
      out.write("                            <div class=\"searchBarCont\">\r\n");
      out.write("                                <input type=\"text\" class=\"searchBar\" placeholder=\"Search\" onkeydown=\"event.key == 'Enter'? window.location.href = 'pages/ShopingListPage/index.jsp?q='+this.value:''\">\r\n");
      out.write("                                <i class=\"fas fa-search searchIcon\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"userAccountAndCart\">\r\n");
      out.write("                            <div class=\"cartImage\">\r\n");
      out.write("                                <img src=\"./assets/icons/cart.svg\" alt=\"icon\" class=\"cartIcon\">\r\n");
      out.write("                                <h4 class=\"color_white mobile_disable\">Cart</h4>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"userAccountImage\">\r\n");
      out.write("                                <i class=\"fa-regular fa-user\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </section>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"bodyContainer\">\r\n");
      out.write("                    <div class=\"bodyContFlex\">\r\n");
      out.write("                        <div class=\"sideBar\">\r\n");
      out.write("                            <div class=\"sideBarBody\">\r\n");
      out.write("                                <ul class=\"sideBarList\">\r\n");
      out.write("                                    <!-- <li class=\"liDropdown\">\r\n");
      out.write("                                        <span>Essentials</span>\r\n");
      out.write("                                        <div class=\"dropdownCont\">\r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    All\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    Dals & Pulses\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    Ghee & Oils\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    Atta & Flours\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    Masalas & Spices\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    Rice & Rice Products\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    Dry Fruits, Nuts & Seeds\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    Sugar, Jaggery & Salt\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li>-->\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"bodyMain\">\r\n");
      out.write("                        <section class=\"hero\">\r\n");
      out.write("                            <div class=\"hero_image\">\r\n");
      out.write("                                <div class=\"imagecontainment imagePrimaryHero\">\r\n");
      out.write("                                    <div class=\"txtdta\">\r\n");
      out.write("                                        all fresh and budget friendly, just for you!\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"imagecontainment largeImagewidth\">\r\n");
      out.write("                                    <div class=\"dataContCent secondCont\">\r\n");
      out.write("                                        <div class=\"productDivHero\">\r\n");
      out.write("                                            <div class=\"itemListProduct\">\r\n");
      out.write("                                                <img src=\"./assets/image/img1.png\" alt=\"\" class=\"listItem\">\r\n");
      out.write("                                                <div class=\"itemListProductName\">\r\n");
      out.write("                                                    <h4>10 KG</h4>\r\n");
      out.write("                                                    <p class=\"fairDiscount\">&#8377; 100 OFF</p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"itemListProduct\">\r\n");
      out.write("                                                <img src=\"./assets/image/img2.png\" alt=\"\" class=\"listItem\"\r\n");
      out.write("                                                    style=\"width: 83px;\">\r\n");
      out.write("                                                <div class=\"itemListProductName\">\r\n");
      out.write("                                                    <h4>10 KG</h4>\r\n");
      out.write("                                                    <p class=\"fairDiscount\">&#8377; 100 OFF</p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"itemListProduct\">\r\n");
      out.write("                                                <img src=\"./assets/image/img3.png\" alt=\"\" class=\"listItem\"\r\n");
      out.write("                                                    style=\"width: 105px;\">\r\n");
      out.write("                                                <div class=\"itemListProductName\">\r\n");
      out.write("                                                    <h4>10 KG</h4>\r\n");
      out.write("                                                    <p class=\"fairDiscount\">&#8377; 100 OFF</p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"itemListProduct\">\r\n");
      out.write("                                                <img src=\"./assets/image/img4.png\" alt=\"\" class=\"listItem\"\r\n");
      out.write("                                                    style=\"width: 105px;\">\r\n");
      out.write("                                                <div class=\"itemListProductName\">\r\n");
      out.write("                                                    <h4>10 KG</h4>\r\n");
      out.write("                                                    <p class=\"fairDiscount\">&#8377; 100 OFF</p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"itemListProduct\">\r\n");
      out.write("                                                <img src=\"./assets/image/img5.png\" alt=\"\" class=\"listItem\"\r\n");
      out.write("                                                    style=\"width: 120px;\">\r\n");
      out.write("                                                <div class=\"itemListProductName\">\r\n");
      out.write("                                                    <h4>10 KG</h4>\r\n");
      out.write("                                                    <p class=\"fairDiscount\">&#8377; 100 OFF</p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </section>\r\n");
      out.write("                        <section class=\"famProduct\">\r\n");
      out.write("                            <h1>Top Deal Made for you</h1>\r\n");
      out.write("                            <div class=\"productMnd\">\r\n");
      out.write("                                <div class=\"productMnd\">\r\n");
      out.write("                                    <div class=\"productDes\">\r\n");
      out.write("                                        <div class=\"productDes_heading\">Shop for 600 to get discount</div>\r\n");
      out.write("                                        <div class=\"productDes_subheading\">\r\n");
      out.write("                                            <div class=\"productDes_imagecont\">\r\n");
      out.write("                                                <img src=\"./assets/image/dairy.png\" alt=\"\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"productDes_details\">\r\n");
      out.write("                                                <h1>Ananda Ghee 100ml.. </h1>\r\n");
      out.write("                                                <h3>100ml Cartoon</h3>\r\n");
      out.write("                                                <p>Expire 13 Nov 2022</p>\r\n");
      out.write("                                                <h2>&#8377;1</h2>\r\n");
      out.write("                                                <p>Current Price: &#8377;54</p>\r\n");
      out.write("                                                <div class=\"addcartbtnRound\">\r\n");
      out.write("                                                    <span>Add Item</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"productMnd\">\r\n");
      out.write("                                    <div class=\"productDes\">\r\n");
      out.write("                                        <div class=\"productDes_heading\">Shop for 600 to get discount</div>\r\n");
      out.write("                                        <div class=\"productDes_subheading\">\r\n");
      out.write("                                            <div class=\"productDes_imagecont\">\r\n");
      out.write("                                                <img src=\"./assets/image/dairy.png\" alt=\"\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"productDes_details\">\r\n");
      out.write("                                                <h1>Ananda Ghee 100ml.. </h1>\r\n");
      out.write("                                                <h3>100ml Cartoon</h3>\r\n");
      out.write("                                                <p>Expire 13 Nov 2022</p>\r\n");
      out.write("                                                <h2>&#8377;1</h2>\r\n");
      out.write("                                                <p>Current Price: &#8377;54</p>\r\n");
      out.write("                                                <div class=\"addcartbtnRound\">\r\n");
      out.write("                                                    <span>Add Item</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </section>\r\n");
      out.write("                        <section class=\"topPickForYou\">\r\n");
      out.write("                            <div class=\"topPick_header\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <h1>Top Pick For You</h1>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <div class=\"topPick_header_btn\">\r\n");
      out.write("                                        <span>View All</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"topPick_body\">\r\n");
      out.write("                                <div class=\"topPick_body_item\">\r\n");
      out.write("                                    <div class=\"topPick_body_item_image\">\r\n");
      out.write("                                        <img src=\"./assets/image/img1.png\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"topPick_body_item_details\">\r\n");
      out.write("                                        <div class=\"topPick_body_item_details_heading\">\r\n");
      out.write("                                            <h3>More Light Extra Power\r\n");
      out.write("                                                Detergent Powder 4 kg</h3>\r\n");
      out.write("                                            <div class=\"topPick_price\">\r\n");
      out.write("                                                <h1 class=\"productPrice\">&#8377;222</h1>\r\n");
      out.write("                                                <h3 class=\"productActualPrice\">425</h3>\r\n");
      out.write("                                                <h4 class=\"productDiscount\">50% off</h4>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"addtoCartBtnClick\">\r\n");
      out.write("                                                <span>Add Item</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"topPick_body_item\">\r\n");
      out.write("                                    <div class=\"topPick_body_item_image\">\r\n");
      out.write("                                        <img src=\"./assets/image/img1.png\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"topPick_body_item_details\">\r\n");
      out.write("                                        <div class=\"topPick_body_item_details_heading\">\r\n");
      out.write("                                            <h3>More Light Extra Power\r\n");
      out.write("                                                Detergent Powder 4 kg</h3>\r\n");
      out.write("                                            <div class=\"topPick_price\">\r\n");
      out.write("                                                <h1 class=\"productPrice\">&#8377;222</h1>\r\n");
      out.write("                                                <h3 class=\"productActualPrice\">425</h3>\r\n");
      out.write("                                                <h4 class=\"productDiscount\">50% off</h4>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"addtoCartBtnClick\">\r\n");
      out.write("                                                <span>Add Item</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"topPick_body_item\">\r\n");
      out.write("                                    <div class=\"topPick_body_item_image\">\r\n");
      out.write("                                        <img src=\"./assets/image/img1.png\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"topPick_body_item_details\">\r\n");
      out.write("                                        <div class=\"topPick_body_item_details_heading\">\r\n");
      out.write("                                            <h3>More Light Extra Power\r\n");
      out.write("                                                Detergent Powder 4 kg</h3>\r\n");
      out.write("                                            <div class=\"topPick_price\">\r\n");
      out.write("                                                <h1 class=\"productPrice\">&#8377;222</h1>\r\n");
      out.write("                                                <h3 class=\"productActualPrice\">425</h3>\r\n");
      out.write("                                                <h4 class=\"productDiscount\">50% off</h4>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"addtoCartBtnClick\">\r\n");
      out.write("                                                <span>Add Item</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </section>\r\n");
      out.write("                        <section class=\" footer makerDetails\">\r\n");
      out.write("                            <div class=\"footerAbout\">\r\n");
      out.write("                                <div class=\"aboutTxt\">About</div>\r\n");
      out.write("                                <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea perferendis vel itaque at\r\n");
      out.write("                                    dolore nisi animi laboriosam quibusdam harum, aliquam maiores dicta non distinctio\r\n");
      out.write("                                    facilis unde tempora odit hic optio.</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"footerContact\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <span><i class=\"fa-solid fa-address-book\"></i></span>\r\n");
      out.write("                                    <span>Contact</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <span><i class=\"fa-brands fa-facebook-f\"></i></span>\r\n");
      out.write("                                    <span>Facebook</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <span><i class=\"fa-brands fa-instagram\"></i></span>\r\n");
      out.write("                                    <span>Instagram</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <span><i class=\"fa-brands fa-twitter\"></i></span>\r\n");
      out.write("                                    <span>Twitter</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"footerTermPolicy\">\r\n");
      out.write("                                <div>term and use</div>\r\n");
      out.write("                                <div>Privecy Policy</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </section>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"cartModel\" class=\"cartModel\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modelData\">\r\n");
      out.write("                    <div class=\"titleModel\">\r\n");
      out.write("                        <div class=\"modelTitleFirst\">\r\n");
      out.write("                            <h2>My Cart</h2>\r\n");
      out.write("                            <span class=\"closeModelCart\">\r\n");
      out.write("                                <img src=\"./assets/icons/right-arrow.png\" alt=\"\">\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <hr width=\"100%\" style=\"background-color: #000;\">\r\n");
      out.write("                        <div class=\"modelTitleSecond\">\r\n");
      out.write("                            <h4>Delivery In 26 Minuts.</h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"itemBody\">\r\n");
      out.write("                        <div class=\"itemDetails\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"billDetails\">\r\n");
      out.write("                            <div class=\"billDetailsExt\">\r\n");
      out.write("                                <h3>Bill Details</h3>\r\n");
      out.write("                                <h6>\r\n");
      out.write("                                    <span>MRP</span>\r\n");
      out.write("                                    <span>&#8377;0</span>\r\n");
      out.write("                                </h6>\r\n");
      out.write("                                <h6>\r\n");
      out.write("                                    <span>Total Discount</span>\r\n");
      out.write("                                    <span>&#8377;0</span>\r\n");
      out.write("                                </h6>\r\n");
      out.write("                                <h6>\r\n");
      out.write("                                    <span>Packing Charges</span>\r\n");
      out.write("                                    <span>&#8377;0</span>\r\n");
      out.write("                                </h6>\r\n");
      out.write("                                <h6>\r\n");
      out.write("                                    <span>Delivery Charges</span>\r\n");
      out.write("                                    <span>&#8377;0</span>\r\n");
      out.write("                                </h6>\r\n");
      out.write("                                <h6>\r\n");
      out.write("                                    <span>Total</span>\r\n");
      out.write("                                    <span>&#8377;0</span>\r\n");
      out.write("                                </h6>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"billPrice\">\r\n");
      out.write("                        <button class=\"payButton\">\r\n");
      out.write("                            <h2>2 items &#149; &#8377;859 &#8377;146 Proceed</h2>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"overlay\"></div>\r\n");
      out.write("        <iframe class=\"profilePopupIFrame\" src=\"./pages/Login Page/index.jsp\" frameborder=\"0\"></iframe>\r\n");
      out.write("        ");
 
			String strb = obj.cartGet("9660102328");
		
      out.write("\r\n");
      out.write("		<script>\r\n");
      out.write("			var cart = ");
      out.print(strb);
      out.write("\r\n");
      out.write("		</script>\r\n");
      out.write("		\r\n");
      out.write("        <script src=\"./localDatabase.js\"></script>\r\n");
      out.write("        <script src=\"./assets/JS/loginPopupFrame.js\"></script>\r\n");
      out.write("        <script src=\"./script.js\"></script>\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
